"""sync_database_schema_with_models

Revision ID: 6760b2b90637
Revises: d042f4b80ecd
Create Date: 2025-12-03 04:37:34.590339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6760b2b90637'
down_revision = 'd042f4b80ecd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_doctors_deleted_at', table_name='doctors')
    op.drop_index('ix_doctors_department', table_name='doctors')
    op.drop_index('ix_doctors_license_number', table_name='doctors')
    op.drop_index('ix_doctors_specialization', table_name='doctors')
    op.create_unique_constraint(None, 'doctors', ['license_number'])
    op.drop_constraint('doctors_user_id_fkey', 'doctors', type_='foreignkey')
    op.create_foreign_key(None, 'doctors', 'users', ['user_id'], ['id'])
    op.drop_index('ix_workers_id', table_name='medical_staff')
    op.create_index(op.f('ix_medical_staff_id'), 'medical_staff', ['id'], unique=False)
    op.drop_index('ix_patients_deleted_at', table_name='patients')
    op.drop_index('ix_patients_medical_record_number', table_name='patients')
    op.create_unique_constraint(None, 'patients', ['medical_record_number'])
    op.drop_constraint('patients_user_id_fkey', 'patients', type_='foreignkey')
    op.create_foreign_key(None, 'patients', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('undefined', 'admin', 'doctor', 'medical_staff', 'patient', 'receptionist', name='userrole'),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'undefined'::userrole"))
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('undefined', 'admin', 'doctor', 'medical_staff', 'patient', 'receptionist', name='userrole'),
               existing_nullable=False,
               existing_server_default=sa.text("'undefined'::userrole"))
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.create_foreign_key('patients_user_id_fkey', 'patients', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'patients', type_='unique')
    op.create_index('ix_patients_medical_record_number', 'patients', ['medical_record_number'], unique=False)
    op.create_index('ix_patients_deleted_at', 'patients', ['deleted_at'], unique=False)
    op.drop_index(op.f('ix_medical_staff_id'), table_name='medical_staff')
    op.create_index('ix_workers_id', 'medical_staff', ['id'], unique=False)
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.create_foreign_key('doctors_user_id_fkey', 'doctors', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'doctors', type_='unique')
    op.create_index('ix_doctors_specialization', 'doctors', ['specialization'], unique=False)
    op.create_index('ix_doctors_license_number', 'doctors', ['license_number'], unique=False)
    op.create_index('ix_doctors_department', 'doctors', ['department'], unique=False)
    op.create_index('ix_doctors_deleted_at', 'doctors', ['deleted_at'], unique=False)
    # ### end Alembic commands ###
