"""add phone and other fields to users table

Revision ID: 97e19a832ff2
Revises: dd6918e75e16
Create Date: 2025-12-02 22:45:30.546424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97e19a832ff2'
down_revision = 'dd6918e75e16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # These columns may already exist from the unified architecture migration
    # Skip adding them if they already exist
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_columns = [col['name'] for col in inspector.get_columns('users')]
    
    if 'phone' not in existing_columns:
        op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    if 'city' not in existing_columns:
        op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    if 'age' not in existing_columns:
        op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    if 'address' not in existing_columns:
        op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    if 'gender' not in existing_columns:
        op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('users', 'address')
    op.drop_column('users', 'age')
    op.drop_column('users', 'city')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
