"""add phone and other fields to users table

Revision ID: 97e19a832ff2
Revises: dd6918e75e16
Create Date: 2025-12-02 22:45:30.546424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97e19a832ff2'
down_revision = 'dd6918e75e16'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('users', 'address')
    op.drop_column('users', 'age')
    op.drop_column('users', 'city')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
