"""add_hospitalizations_table

Revision ID: bb649bc3aec3
Revises: c1d2e3f4g5h6
Create Date: 2025-12-03 14:26:14.048547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bb649bc3aec3'
down_revision = 'c1d2e3f4g5h6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitalizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('admission_date', sa.DateTime(), nullable=False),
    sa.Column('discharge_date', sa.DateTime(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitalizations_id'), 'hospitalizations', ['id'], unique=False)
    op.create_index(op.f('ix_hospitalizations_patient_id'), 'hospitalizations', ['patient_id'], unique=False)
    op.drop_index('idx_receptionists_name', table_name='receptionists')
    op.drop_index('ix_receptionists_id', table_name='receptionists')
    op.drop_table('receptionists')
    op.drop_index('idx_workers_name', table_name='workers')
    op.drop_index('ix_workers_id', table_name='workers')
    op.drop_table('workers')
    op.drop_index('ix_doctors_deleted_at', table_name='doctors')
    op.drop_index('ix_doctors_department', table_name='doctors')
    op.drop_index('ix_doctors_license_number', table_name='doctors')
    op.drop_index('ix_doctors_specialization', table_name='doctors')
    op.create_unique_constraint(None, 'doctors', ['license_number'])
    op.drop_constraint('doctors_user_id_fkey', 'doctors', type_='foreignkey')
    op.create_foreign_key(None, 'doctors', 'users', ['user_id'], ['id'])
    op.drop_index('ix_medical_staff_user_id', table_name='medical_staff')
    op.drop_index('ix_patients_deleted_at', table_name='patients')
    op.drop_index('ix_patients_medical_record_number', table_name='patients')
    op.create_unique_constraint(None, 'patients', ['medical_record_number'])
    op.drop_constraint('patients_user_id_fkey', 'patients', type_='foreignkey')
    op.create_foreign_key(None, 'patients', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.drop_index('ix_users_deleted_at', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_deleted_at', 'users', ['deleted_at'], unique=False)
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.create_foreign_key('patients_user_id_fkey', 'patients', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'patients', type_='unique')
    op.create_index('ix_patients_medical_record_number', 'patients', ['medical_record_number'], unique=False)
    op.create_index('ix_patients_deleted_at', 'patients', ['deleted_at'], unique=False)
    op.create_index('ix_medical_staff_user_id', 'medical_staff', ['user_id'], unique=False)
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.create_foreign_key('doctors_user_id_fkey', 'doctors', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'doctors', type_='unique')
    op.create_index('ix_doctors_specialization', 'doctors', ['specialization'], unique=False)
    op.create_index('ix_doctors_license_number', 'doctors', ['license_number'], unique=False)
    op.create_index('ix_doctors_department', 'doctors', ['department'], unique=False)
    op.create_index('ix_doctors_deleted_at', 'doctors', ['deleted_at'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='workers_pkey')
    )
    op.create_index('ix_workers_id', 'workers', ['id'], unique=False)
    op.create_index('idx_workers_name', 'workers', ['first_name', 'last_name'], unique=False)
    op.create_table('receptionists',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='receptionists_pkey')
    )
    op.create_index('ix_receptionists_id', 'receptionists', ['id'], unique=False)
    op.create_index('idx_receptionists_name', 'receptionists', ['first_name', 'last_name'], unique=False)
    op.drop_index(op.f('ix_hospitalizations_patient_id'), table_name='hospitalizations')
    op.drop_index(op.f('ix_hospitalizations_id'), table_name='hospitalizations')
    op.drop_table('hospitalizations')
    # ### end Alembic commands ###
