"""Add appointments table

Revision ID: d8706cfc50cf
Revises: d4e5f6g7h8i9
Create Date: 2025-12-04 15:59:36.417205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8706cfc50cf'
down_revision = 'd4e5f6g7h8i9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('appointment_date', sa.DateTime(), nullable=False),
    sa.Column('disease', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index('ix_appointments_date_deleted', 'appointments', ['appointment_date', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_appointments_deleted_at'), 'appointments', ['deleted_at'], unique=False)
    op.create_index('ix_appointments_doctor_date', 'appointments', ['doctor_id', 'appointment_date', 'deleted_at'], unique=False)
    op.create_index('ix_appointments_doctor_deleted', 'appointments', ['doctor_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index('ix_appointments_patient_deleted', 'appointments', ['patient_id', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index('ix_appointments_status_deleted', 'appointments', ['status', 'deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_appointments_status_deleted', table_name='appointments')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index('ix_appointments_patient_deleted', table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_index('ix_appointments_doctor_deleted', table_name='appointments')
    op.drop_index('ix_appointments_doctor_date', table_name='appointments')
    op.drop_index(op.f('ix_appointments_deleted_at'), table_name='appointments')
    op.drop_index('ix_appointments_date_deleted', table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
