"""update receptionist and worker models to use user_id foreign key

Revision ID: dd6918e75e16
Revises: rgmqjko6hdnp
Create Date: 2025-12-02 21:52:23.446766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd6918e75e16'
down_revision = 'rgmqjko6hdnp'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Delete existing data since we're changing the schema fundamentally
    # Old data doesn't have user_id references and can't be migrated
    op.execute('DELETE FROM receptionists')
    op.execute('DELETE FROM workers')
    
    # Receptionists table changes
    op.add_column('receptionists', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('receptionists', sa.Column('shift_schedule', sa.String(length=255), nullable=True))
    op.add_column('receptionists', sa.Column('desk_number', sa.String(length=50), nullable=True))
    op.add_column('receptionists', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index('idx_receptionists_name', table_name='receptionists')
    op.create_unique_constraint(None, 'receptionists', ['user_id'])
    op.create_foreign_key(None, 'receptionists', 'users', ['user_id'], ['id'])
    op.drop_column('receptionists', 'last_name')
    op.drop_column('receptionists', 'first_name')
    op.drop_column('receptionists', 'phone')
    
    # Drop indexes on users table if they exist
    op.execute('DROP INDEX IF EXISTS ix_users_deleted_at')
    op.execute('DROP INDEX IF EXISTS ix_users_first_name')
    op.execute('DROP INDEX IF EXISTS ix_users_last_name')
    op.execute('DROP INDEX IF EXISTS ix_users_role')
    
    # Workers table changes
    op.add_column('workers', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('workers', sa.Column('job_title', sa.String(length=100), nullable=True))
    op.add_column('workers', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('workers', sa.Column('shift_schedule', sa.String(length=255), nullable=True))
    op.add_column('workers', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_index('idx_workers_name', table_name='workers')
    op.create_unique_constraint(None, 'workers', ['user_id'])
    op.create_foreign_key(None, 'workers', 'users', ['user_id'], ['id'])
    op.drop_column('workers', 'last_name')
    op.drop_column('workers', 'first_name')
    op.drop_column('workers', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('workers', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('workers', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workers', type_='foreignkey')
    op.drop_constraint(None, 'workers', type_='unique')
    op.create_index('idx_workers_name', 'workers', ['first_name', 'last_name'], unique=False)
    op.drop_column('workers', 'deleted_at')
    op.drop_column('workers', 'shift_schedule')
    op.drop_column('workers', 'department')
    op.drop_column('workers', 'job_title')
    op.drop_column('workers', 'user_id')
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_last_name', 'users', ['last_name'], unique=False)
    op.create_index('ix_users_first_name', 'users', ['first_name'], unique=False)
    op.create_index('ix_users_deleted_at', 'users', ['deleted_at'], unique=False)
    op.add_column('receptionists', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('receptionists', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('receptionists', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'receptionists', type_='foreignkey')
    op.drop_constraint(None, 'receptionists', type_='unique')
    op.create_index('idx_receptionists_name', 'receptionists', ['first_name', 'last_name'], unique=False)
    op.drop_column('receptionists', 'deleted_at')
    op.drop_column('receptionists', 'desk_number')
    op.drop_column('receptionists', 'shift_schedule')
    op.drop_column('receptionists', 'user_id')
    # ### end Alembic commands ###
